name: CI for Frontend
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ayule/react-test -f Dockerfile.dev .

      - name: Test Docker image
        run: docker run -e CI=true ayule/react-test npm test
